In [148]:
# Step 1: Import Numpy Library
import numpy as np

In [149]:
# This is how we print numpy version: np.__version__

In [ ]:
# Create two equivalent 2D arrays using different np.array inputs
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array(([1,2,3],[4,5,6]))
# array3 = np.array([1,2,3],[4,5,6]) - This will give error because if you check the api documentation for thre np.array function second expected argument is datatype as per function defination

In [ ]:
# Inspect the first array and its shape
print(array1)
array1.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
# Inspect the second array and its shape
print(array2)
array2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
# Check the scalar type stored in the array
a = np.array([1,2,3,4,5,6],)
# a[0] = np.dtype(5) -> This will givve error because we are using data type here for wrong purpose

print(type(a[0]))

<class 'numpy.int64'>


In [ ]:
# Create an int16 array to show explicit dtype handling
b = np.array([1,2,3], np.int16)
# b[0] = 1231212321 - Here if we try to assign a big value that does not fit into the range then it will give error overflow

In [71]:
# How to perform slicing operation on numpay array
a[3:]
a[:3]
# Both of the above mentioned give different output since they both are serving different purpose

array([1, 2, 3])

In [72]:
# Concept - In case we are performing slicing operation on numpay array then it returns a view of th array, it does not give a copy of the list
# Step 1 : Let's do this witn Numpy
b = a[:3]
print(a,b)
# print(type(a), type(b))

b[0] = 212
print(a,b)
print(b.base)


# Step 2: Let's do this with Python
a_pyton = [1,2,3,4,5,6]
b_python = a[:3]
print(a_pyton, b_python);
b_python[0]=212
print(a_pyton, b_python);

[1 2 3 4 5 6] [1 2 3]
[212   2   3   4   5   6] [212   2   3]
[212   2   3   4   5   6]
[1, 2, 3, 4, 5, 6] [212   2   3]
[1, 2, 3, 4, 5, 6] [212   2   3]


In [76]:
# How to determine if the return of numpy function is a view or a copy of the original array

array = np.array([1,2,3])
array

array_view = array[:1]
array_copy = array.copy()
print(array_view.base, array_copy.base)
# Here we get None, it shows that it is a copy of the original array
# These type of functionality are not present in python, but numpy library supports this.

[1 2 3] None


In [80]:
# Multi Dimension Array in Numpy
m_array = np.array([[1,2,3],[4,5,6]])
m_array.nbytes

48

In [98]:
# Creating 2 Dimensional Matrix in Numpy library
array_2d = np.array([[1,2,3,],[4,5,6]])

print(array_2d.shape, array_2d[1,2])
array_2d

(2, 3) 6


array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
# Let's learn about 1-D Array
array_1d = np.array([2])
print(array_1d.shape)

# 0D array - Scalar
array_0d = np.array(3)
# print(array_0d.ndim) --->Here the ndim = 0, because it is a 0D Array

(1,)
0


In [ ]:
# Check the array rank and shape of the 2D matrix
print(array_2d.ndim)
print(array_2d.shape)

2
(2, 3)


In [147]:
# Creating a 3 D Matrix in Numpy
array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(array_3d.ndim)
print(len(array_3d.shape) == array_3d.ndim)
print(array_3d.size)

# How to extract the shape into variable at run time
# Remember np.shape returns a tuple, now this tuple that is returned from here is orderede and unchangeable
shapetuple = array_3d.shape
print("Shape is :",array_3d.shape)
(x,*_) = shapetuple;
print(x, len(shapetuple))

3
True
8
Shape is : (2, 2, 2)
2 3


In [163]:
# Next Topic to learn: np.zeroes(), np.ones(), np.empty(), np.arange(), np.linspace()

oned_zero_array = np.zeros(tuple([2]))
print(oned_zero_array.dtype)

float64


In [190]:
# print(type([2])) --Here it means that it is a object of class list.


# In case you want to explicitly set the data type as float32 instead of float64
two_d_zeroes_array = np.zeros(tuple([2,2]),np.float32);
print(type((two_d_zeroes_array[0]).shape))
two_d_zeroes_array[0].dtype

<class 'tuple'>


dtype('float32')

In [176]:
# Function to check whether the data is iterable or not
def is_iterable(obj):
    try:
        iter(obj)
        return True
    except TypeError:
        return False

is_iterable([2])

True

In [193]:
# Array filled with one instead of filled with zero
np.ones((1,2))

array([[1., 1.]])

In [204]:
# This is how you can create a array within a given range
np.arange(0,10,2)

np.arange(-3,3,0.5,dtype = np.int16)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8], dtype=int16)

In [ ]:
# Generate evenly spaced values with linspace
print(np.linspace(0,10,num = 5))
print(np.linspace(0,10,num = 5, dtype= np.int16))

[ 0.   2.5  5.   7.5 10. ]
[ 0  2  5  7 10]


In [252]:
# Concept: Sorting in numpy
lin_space_array = np.linspace(0,100,5)

np.sort(lin_space_array, axis = -1, kind = "heapsort")

# Concept Concatenation in numpy
# 1-d array
array1 = np.arange(1,5,1)
array2 = np.arange(5,10,1)
np.concatenate((array1,array2))

# 2-d array
array_2d_1 = np.array([[1,2],[3,4]])
array_2d_2 = np.array([[5,6],[7,8]])
np.concatenate((array_2d_1, array_2d_2),axis = array_2d_1.shape[0]-1)

array_2d_3 = np.array([[5,6],[7,8],[9,10]])

print(array_2d_1.shape, array_2d_3.shape)
np.concatenate((array_2d_1, array_2d_3))

(2, 2) (3, 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [269]:
# Reshape a matrix - Important point is that the number of element will remain the same - size remain same
array = np.arange(0,12,1)
array2 = np.reshape(array,array.size)
array2[0] = 1212

# print(array[0], array2[0]) This shows that if we reshape the matrix then it just give us a new view

shape1 = np.reshape(array,(3,4),)
shape2 = np.reshape(array,(6,2))

print(shape1.shape, shape2.shape)

shape2[5][0] = 3435
# print(array, shape1, shape2)This shows that we are getting view in return

(3, 4) (6, 2)
[1212    1    2    3    4    5    6    7    8    9 3435   11] [[1212    1    2    3]
 [   4    5    6    7]
 [   8    9 3435   11]] [[1212    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]
 [3435   11]]


In [300]:
# How to add a new dimension
array = np.linspace(1,12,12)
array = np.expand_dims(array, axis = 1)

In [325]:
# Indexing or Slicing in Numpy
# Concept 1: Here, I first need to learn about how we can perform indexing and slicing on the data
array = np.array([[1,2,3,4],[5,6,7,8]])
array[0][0:]

# print(array[array<5])

array_bool = np.array([[True, True, True],[False, False, False]])
print(array_bool[array_bool]);

print(array[array%2 ==0]);

print(type(array_bool[0][0]))

[ True  True  True]
[2 4 6 8]
<class 'numpy.bool'>


In [333]:
# Concept: How to create array from existing data
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

vstack_array = np.concatenate((a1,a2), axis = 0)
hstack_array = np.concatenate((a1,a2), axis = 1)

print(vstack_array)
print(hstack_array)

hstack = np.hstack((a1,a2))
vstack = np.vstack((a1,a2))

print(vstack)
print(hstack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [345]:
# Basic Array Operation
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

# Sum of two matrix
sum_matrix = np.add(matrix1, matrix2)
print(sum_matrix)

# Addition of two matrix in python
matrix3 = matrix1 + matrix2
print(matrix3)

# Here for both above operation result is same, but one use Python loop for calcualtion and other use direct c compiled code for caluclation.
# Due to this reason numpy is faster than python add operation and that's why all other library use the concept of numpy for performing matrix operation


# Subtraction of two matrix
matrix4 = np.subtract(matrix3, matrix2)
print(matrix4.base)

matrix5 = matrix3 - matrix2;
# print(matrix5.base) - None - This simply shows that there is copy returnd over ehre

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
None
None


In [ ]:
# Show broadcasting with 1D and 2D arrays
import numpy as np
distance_km = np.array([4,2,6,1,7]);
distance_km = distance_km * 1.6
distance_km

array_1 = np.array([1,2,3])
array_2 = np.array([[1,2,3]])

print(array_1.ndim,array_2.ndim); 
print(array_1.shape,array_2.shape); 

np.add(array_1, array_2)

print(array_1 + array_2)


1 2
(3,) (1, 3)
[[2 4 6]]


In [33]:
# Array operations: maximum, minimum, sum
np.max(array_2, axis = 0)
np.min(array_2, axis = 0)
np.sum(array_1, axis = 0)


array_3 = np.array([[1,2,3], [4,5,6]])
print(array_3)

np.mean(array_3, axis = 0)
np.prod(array_3, axis = 0)
np.std(array_3)

[[1 2 3]
 [4 5 6]]


np.float64(1.707825127659933)

In [ ]:
# Transpose the matrix using different NumPy APIs
matrix_1 = np.array([[1,2,3],[4,5,6]])
matrix_1.transpose()
np.transpose(matrix_1)

matrix_1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Reshape the matrix into different compatible shapes
matrix = np.array([[1,2,1], [4,5,6]])
np.reshape(matrix, (3,2))
matrix = np.array([[1,2], [1,4], [5,6]])
np.reshape(matrix, (2,3))

array([[1, 2, 1],
       [4, 5, 6]])

In [ ]:
# Find unique values and the count of non-zero entries
np.unique(matrix)
np.count_nonzero(matrix)

np.int64(6)

In [73]:
# Flatten array - used for converting array into 1D array
matrix.flatten()

array([1, 2, 1, 4, 5, 6])